<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-LNAFOEG" failures="1" tests="4" name="Test" time="46.896" errors="0" timestamp="2024-04-01T07:24:44 IST">
  <testcase classname="com.quafox.tests.Login" name="verifyLoginWithValidCredentials" time="1.778"/>
  <testcase classname="com.quafox.tests.Login" name="verifyLoginWithInvalidCredentials" time="11.473"/>
  <testcase classname="com.quafox.tests.Login" name="verifyLoginWithInvalidUsername" time="1.514"/>
  <testcase classname="com.quafox.tests.Login" name="verifyLoginWithInvalidPassword" time="1.39">
    <failure type="java.lang.AssertionError" message="expected [Warning: No match for E-Mail Address and/or Password.] but found [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.]">
      <![CDATA[java.lang.AssertionError: expected [Warning: No match for E-Mail Address and/or Password.] but found [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.]
at com.quafox.tests.Login.verifyLoginWithInvalidPassword(Login.java:97)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginWithInvalidPassword -->
</testsuite> <!-- Test -->
